Método post na rota newsletter
ClaudioMascaro/Claudio-News-API pull request #4
Opened 2020-12-22 01:19 UTC by ClaudioMascaro

Tive problemas com o PR anterior e a única solução foi recriar, tentando evitar os erros. Acho que dessa vez não estou recriando os arquivos, só não sei se criei o controller da forma esperada

2020-12-22 10:39 UTC, nawarian requested changes

2020-12-22 10:39 UTC, nawarian commented on src/controllers/mailingController.ts
> +  async include (email: string) {
O seu controller tá bem isoladinho, bonitinho. Mas sem lidar com request/response ele virou um Service.

Receba `req` e `res` como parâmetros no seu controller. Recomendo também criar um service que faz exatamente o que este método `include()` está fazendo. Então aqui você vai usar este service. Algo assim:

```js
async include (req: Request, res: Response) {
  // validação e o que mais precisar...
  newsletterService.include(req.body.email);
  // validação e o que mais precisar...
}
```

2020-12-22 14:57 UTC, ClaudioMascaro commented on src/controllers/mailingController.ts
> +  async include (email: string) {
Certo, dei merge nas duas rotas e configurei como pedido :)

2020-12-22 18:03 UTC, nawarian requested changes

2020-12-22 18:03 UTC, nawarian commented on src/controllers/mailingController.ts
> +      const emailInclude = new NewsletterService()
Fazer `new QualquerService()` não é recomendável. Dessa forma você acaba usando mais memória do que o necessário.

No arquivo `NewsletterSubscriptionService` faça um `export default new NewsletterService()`. Dessa forma o seu import vai ser o objeto instanciado.

Então aqui você poderá utilizar assim:

```js
import newsletterService from '../services/NewsletterSubscriptionService'
...


await newsletterService.subscribe(email)
...
```

2020-12-22 18:03 UTC, nawarian commented on src/routes/newsletter.routes.ts
> +const newsletterSubscription = new Newsletter().include
A mesma dica do export default se aplica aqui.

2020-12-22 18:27 UTC, ClaudioMascaro commented on src/controllers/mailingController.ts
> +      const emailInclude = new NewsletterService()
Corrigido no último commit!

2020-12-23 07:35 UTC, nawarian approved these changes

2020-12-23 11:41 UTC, merged