Validação de e-mail com Joi
ClaudioMascaro/Claudio-News-API pull request #6
Opened 2020-12-22 03:03 UTC by ClaudioMascaro

Feature de validação com máximo de 32 caracteres no usuário, @, 221 caracteres no domínio (total 254) por padrão no .email

2020-12-22 10:52 UTC, nawarian requested changes

2020-12-22 10:52 UTC, nawarian commented on src/controllers/mailingController.ts
> +const emailSchema = Joi.object().keys({
Extrai esse `emailSchema` pra um arquivo só. Dessa forma você consegue reutilizar esse mesmo schema em outros lugares da aplicação quando precisar. Poderá talvez até mesmo extrair para usar no front-end mais tarde.

2020-12-22 10:52 UTC, nawarian commented on src/controllers/mailingController.ts
> +      if (validateEmail.error)
IFs sem chaves `{ }` costumam ser fonte de problemas. Recomendo utilizar chaves mesmo se o corpo do IF tiver apenas uma linha.

2020-12-22 10:52 UTC, nawarian commented on src/controllers/mailingController.ts
>        await mailing.save()
Se não me engano você pode fazer um `return await mailing.save()` direto.

2020-12-22 15:31 UTC, ClaudioMascaro commented on src/controllers/mailingController.ts
> +const emailSchema = Joi.object().keys({
Feito

2020-12-22 15:31 UTC, ClaudioMascaro commented on src/controllers/mailingController.ts
> +      if (validateEmail.error)
Chaves colocadas!

2020-12-22 15:31 UTC, ClaudioMascaro commented on src/controllers/mailingController.ts
>        await mailing.save()
Feito, obrigado ;)

2020-12-23 07:36 UTC, nawarian approved these changes

2020-12-23 11:42 UTC, merged